---
bastion_build_packages:
  - curl
  - git
  - rsync
  - qemu-img
  - guestfs-tools
  - libguestfs
  - libguestfs-xfs

guestfs_image: "localhost/wp-fedora-small-guestfs:43"
guestfs_bin_dir: "{{ work_base }}/bin"

guestfs_wrapper_tools:
  - qemu-img
  - virt-customize
  - virt-sysprep
  - virt-df
  - virt-cat
  - virt-ls
  - virt-inspector
  - virt-sparsify
  - virt-resize
  - virt-filesystems
  - guestfish
