---
vm_wait_for_ip: false
vm_power_on: true
vm_ip_fact_name: ""
vm_static_ip: ""
vm_first_boot_pause: 30
vm_arp_retries: 36
vm_arp_retry_delay: 10

vm_vmdk_upload: "{{ datastore_base }}/{{ vm_vmdk_filename }}"
vm_vmdk_final: "{{ datastore_base }}/{{ vm_datastore_folder }}/{{ vm_vmdk_filename }}"
vm_vmdk_local: "{{ vm_build_dir }}/output/disk.vmdk"

govc_cmd: >-
  podman run --rm --env-file {{ govc_env_path }}
  {{ govc_image }} /govc
