FROM registry.fedoraproject.org/fedora:43

# Offline image customization tooling for the vmware-fedora-small track.
RUN dnf -y install \
      qemu-img \
      guestfs-tools \
      libguestfs \
      libguestfs-xfs \
      curl \
    && dnf clean all

ENV LIBGUESTFS_BACKEND=direct
